num1 = int(input("Ingresa el primer número: "))
num2 = int(input("Ingresa el segundo número: "))
num3 = int(input("Ingresa el tercer número: "))
mayor = max(num1, num2, num3)
menor = min(num1, num2, num3)
print("El número mayor es:", mayor)
print("El número menor es:", menor)